require("abhi.plugins-setup")
require("abhi.core.keymaps")
require("abhi.core.options")
--require("abhi.core.colorscheme")
require("abhi.plugins.nvim-tree")
require("abhi.plugins.lualine")
require("abhi.plugins.comment")
require("abhi.plugins.telescope")
require("abhi.plugins.nvim-cmp")
require("abhi.plugins.lsp.mason")
require("abhi.plugins.lsp.lspsaga")
require("abhi.plugins.lsp.lspconfig")
require("abhi.plugins.lsp.null-ls")
require("abhi.plugins.treesitter")
require("abhi.plugins.autotag")
require("abhi.plugins.autopairs")
require("abhi.plugins.colorizer")
require("abhi.plugins.typescript")
require("abhi.plugins.better-comments")
require("abhi.plugins.bufferline")
require("abhi.plugins.alpha")
require("abhi.plugins.lsp.lspkind")
require("abhi.plugins.onedark")

-- require("abhi.plugins.vscode")
-- require("abhi.plugins.material")
-- require("abhi.plugins.neosolarized")
